@echo off
REM ===================================================================
REM PCIS - produce the release package  (Step 4)
REM
REM Cleans, builds, compiles the installer, assembles Release\ and
REM verifies every required file is present.
REM ===================================================================
setlocal EnableDelayedExpansion
cd /d "%~dp0"

echo.
echo === PCIS release ===

echo [1/5] Cleaning previous output...
if exist build   rmdir /s /q build
if exist dist    rmdir /s /q dist
if exist Release rmdir /s /q Release

echo [2/5] Building application...
call build.bat
if errorlevel 1 ( echo [ERROR] Build failed - release aborted. & exit /b 1 )

REM --- Inno Setup ------------------------------------------------------
echo [3/5] Compiling installer...
set "ISCC="
for %%P in (
  "%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe"
  "%ProgramFiles%\Inno Setup 6\ISCC.exe"
  "%ProgramFiles(x86)%\Inno Setup 5\ISCC.exe"
) do if exist %%P set "ISCC=%%P"

if not defined ISCC (
    echo [ERROR] Inno Setup not found.
    echo         Install from https://jrsoftware.org/isdl.php
    echo         The application built OK - only the installer step failed.
    exit /b 1
)
"%ISCC%" installer.iss
if errorlevel 1 ( echo [ERROR] Installer compilation failed. & exit /b 1 )

echo [4/5] Assembling Release folder...
if not exist Release mkdir Release
if exist "installer_output\PCIS_Setup.exe" copy /y "installer_output\PCIS_Setup.exe" "Release\" >nul
if exist LICENSE      copy /y LICENSE      "Release\" >nul
if exist CHANGELOG.md copy /y CHANGELOG.md "Release\" >nul
if exist docs\"User Manual.pdf"  copy /y docs\"User Manual.pdf"  "Release\" >nul
if exist docs\"Release Notes.pdf" copy /y docs\"Release Notes.pdf" "Release\" >nul

echo [5/5] Verifying release contents...
set "MISSING=0"
for %%F in ("Release\PCIS_Setup.exe" "Release\LICENSE" "Release\CHANGELOG.md") do (
    if not exist %%F ( echo   MISSING: %%F & set "MISSING=1" ) else ( echo   ok: %%F )
)
REM PDFs are generated by tools\build_docs.py; warn rather than fail so a
REM missing manual does not block an otherwise good release.
for %%F in ("Release\User Manual.pdf" "Release\Release Notes.pdf") do (
    if not exist %%F ( echo   WARNING: %%F not present ^(run tools\build_docs.py^) )
)

if "%MISSING%"=="1" (
    echo.
    echo [ERROR] Release incomplete - see MISSING entries above.
    exit /b 1
)

echo.
echo === RELEASE OK ===
echo Release\PCIS_Setup.exe
endlocal
